spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 123wjd
    url: mariadb://localhost:3306/test?characterEncoding=UTF-8&serverTimezone=UTC

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql

logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace #show parameter binding
      SQL: DEBUG